[package]
edition = "2021"
name = "rtc-node"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.8.1", default-features = false, features = [
    "async",
    "napi6",
] }
napi-derive = "3.5.0"
livekit-ffi = { path = "./rust-sdks/livekit-ffi" }
prost = "0.14"
prost-types = "0.14"
log = "0.4.20"
tokio = { version = "1.37.0", features = ["full"] }

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = true
